import type { Metadata } from 'next';
import React from 'react';
import localFont from 'next/font/local';
import Providers from '@components/Providers';
import Background from '@components/Background';
import '../globals.css';

const satoshi = localFont({
  src: [
    {
      path: '../assets/fonts/Satoshi-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Satoshi-Italic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../assets/fonts/Satoshi-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Satoshi-BoldItalic.woff2',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-satoshi',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/* <link rel="icon" href="/favicon.ico" sizes="any" /> */}</head>
      <body className={satoshi.className}>
        <Providers>
          <Background>{children}</Background>
        </Providers>
      </body>
    </html>
  );
}
