import React from 'react';
import type { Metadata } from 'next';

import SmoothScrolling from '../../components/SmoothScrolling';

export const metadata: Metadata = {
  title: 'Mikey Holland',
  description: 'Generated by create next app',
};

export default async function ClientLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <SmoothScrolling>{children}</SmoothScrolling>;
}
